// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://twnzcnzzdvruxcnikghn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR3bnpjbnp6ZHZydXhjbmlrZ2huIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU4MjA2ODAsImV4cCI6MjA2MTM5NjY4MH0.Ebvj-Xsp0s17VUOoSr1XAEwoXmP4gHPxEtyXbrqarOM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);